[phases.setup]
    # https://github.com/NixOS/nixpkgs/commits/master/pkgs/development/web/bun/default.nix
    nixpkgsArchive = 'bdac72d387dca7f836f6ef1fe547755fb0e9df61' # https://github.com/NixOS/nixpkgs/commit/bdac72d387dca7f836f6ef1fe547755fb0e9df61